### ISSUE TITLE
Energy bar address

### ISSUE THREAD

**Issue by tuofeichen** [tuofeichen/SmartTree-Electrical#2]
Hey @kevintian18,

Can you take a look at this part ? What's this magic number 50's doing. 

https://github.com/tuofeichen/SmartTree-Electrical/blob/master/SmartTree_Server/TFT.cpp#L44

**Comment by kevintian18** [comment]
50 is the number of daily energy values stored in the Due flash. After 50 values are written, the energy values will wrap around and overwrite the old values. Consider making this number a global constant; either that or consider moving the data to a separate file on the SD card; that way the screen software can update the energy bars without any prompts from the BMS.

**Comment by tuofeichen** [comment]
ohh i see. that's right. ok, we will see if we switch to SD card or not, but definitely gonna clean up the code there a bit. close
